### ISSUE TITLE
Remove intern job url

### ISSUE THREAD

**Issue by JoWilson17** [abletech/abletech.nz#70]
Please remove the following url due to it being scraped (ongoing) and posted by random international job listing companies like Glassdoor and Indeed, resulting in (ongoing) applications from unsuspecting developers.

https://abletech.nz/jobs/front-end-developer-intern/

**Comment by camfowler** [comment]
If possible we should make these a 301 to the jobs page so we don't loose the google juice.

**Comment by JoWilson17** [comment]
> If possible we should make these a 301 to the jobs page so we don't loose the google juice.

I'm getting job applications from intern-hopefuls daily. Places like Glassdoor and Indeed list jobs unsolicited and have refused to remove them if they're 'publicly available' hence my adding this issue.

**Comment by camfowler** [comment]
@JoWilson17 thanks for the update, will bump the priority of removing this.
